name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Debug AWS Credentials
        run: aws sts get-caller-identity

      - name: Authenticate to AWS CodeArtifact
        id: login
        run: |
          export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain demo --domain-owner 048394383216 --region ap-south-1 \
            --query authorizationToken --output text)
          echo "CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_ENV

      - name: Configure Maven to use AWS CodeArtifact
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>demo-demo-repository</id>
                <username>aws</username>
                <password>eyJ2ZXIiOjEsImlzdSI6MTczNDQxMzY3MCwiZW5jIjoiQTEyOEdDTSIsInRhZyI6Il85a3dLT1hHUkZvOVNuTkw5cTZsclEiLCJleHAiOjE3MzQ0NTY4NzAsImFsZyI6IkExMjhHQ01LVyIsIml2IjoiSnVVbXNCaWIxOTNKS3I0USJ9.Z4qDshA4VC1Fg7hvhjBiYQ.e-AQNKOU-3j_4Ptv.uaBsbWu1cQxfQrKdtNcbTETAiu4hrRU3Ij0Lv37WnDiLdegLunM4wFNxxLgpu3HbVLaO-5XDnUXblyH4zK1D_BF3QaKWtrtin7L54VzWlHXfkYkOV5FwAB9YXg_OeS_tq_UapgHvb9QsYEauJDoAbrhG9JZwFGqS4ms_qBOcHqf-GNF7EgBhlvClqbWZyXAdmy8_JcKd8p7kEH-b1j3DBNwAlB4xMaq3Lh8XpuaqrTDLL1jUdJgDnOkPJUJXlG11GW3WOakVwzOYon9SOA_TBiz_6HHmpUKwiAFKGxgLTqPGMlFYaHc31oN9rAw1-JY8f4UwcAKQsEWRVmn-l97q26FXHPXjUsCSIM1aVMG_6DHccQ6OSDrDeYxfV5rif8clYvBcRfxFWTgxWwXtF5fopeMroyLqu-2mLZ-p30b2a-G0U5IHcYtdO3_s9XbmeuS7eqDFj7K3cd04Daf76z_e25D-NuEgidRy8V07W4WrLnRQ5eMTkkue3-pJ_xnXpIFLMMFSAFXlYuNuUaxdYSf_fFIm4XOY3ebT6fUZ6zXl9ARfmD4ud-sdp66XysKeTWLhHcSY9A__fTQSwziFKtQ41jgH9QwYwp7IMTiLiFd4OXKD10gSzPPBTdSJDKESMPK_oL31e7wfjJC1oTmWsuwlLGOwTYdGKWoH4cKnVGZOXi9S7kJqmx-CiQoO40atc300Qf0RHIu3B5S5UjfXqVLDaU6fXkRpwyph8h8JegirGTvkGkCv57XVnE8VkTwH8fXfDh2emQjIqvLKW2BWSTHH_3PPIhfXSTxDn64zwEFvMVkjtDOXaFhXGiwpC1O7Yl_fuynl3N1gMKUVfyybDneNMN0cQeewM_0peppIbDrJWxEm3Abvaft4dlZRVzh1Mdow6c5o9r-Cdoz6Oe_4xEyUqKT2Tof7gDrNfxkp4F7HD1JmYLLYElHBcq9VdsE0L8WF5gICKgBqG0uZtsX669EDyCigtZ5gahRqOlolDOyN7Onf9cBfEZ_UEw.dAEgKpW_hrkyYBS1eqZnsg</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>demo-demo-repository</id>
                <activation>
                  <activeByDefault>true</activeByDefault>
                </activation>
                <repositories>
                  <repository>
                    <id>demo-demo-repository</id>
                    <url>https://demo-048394383216.d.codeartifact.ap-south-1.amazonaws.com/maven/demo-repository/</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
          </settings>
          EOF

      - name: Build and Deploy with Maven
        run: mvn clean deploy --settings ~/.m2/settings.xml
